register:
    path: /
    controller: App\Controller\RegisterController
    action: register
    methods:
      - POST

addPost:
    path: /addpost
    controller: App\Controller\AddPostController
    action: addPost
    methods:
      - POST

post:
    path: /post
    controller: App\Controller\PostController
    action: post
    methods:
        - GET